openapi: 3.0.0
info:
  title: 'Mars Concept Title'
  description: 'Please complete this spec as seen in the module Information Module'
  version: 0.0.1
components:
  securitySchemes:
    userToken:
      type: http
      scheme: bearer
servers:
  - url: http://localhost:8080/
    description: 'Local development implementation'
  - url: https://project-ii.ti.howest.be/mars-03
    description: 'Public web api'
paths:
  /api/message:
    get:
      description: Get a nice message
      operationId: getMessage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string

  /api/user:
    post:
      description: Create a new user
      operationId: createUser
      responses:
        '200':
          description: User created
          content:
            application/json:
              schema:
                type: jsonObject

  /api/users:
    get:
      description: Get all user info
      operationId: getUsers
      security:
        - userToken: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: jsonObject